export const difficultyData = [
  { key: '1', value: 'Any Difficulty' },
  { key: '2', value: 'Easy' },
  { key: '3', value: 'Medium' },
  { key: '4', value: 'Hard' },
];

export const categoriesData = [
  { key: 1, value: 'Any Category' },
  { key: 9, value: 'General Knowledge' },
  { key: 10, value: 'Entertainment: Books' },
  { key: 11, value: 'Entertainment: Film' },
  { key: 12, value: 'Entertainment: Music' },
  { key: 13, value: 'Entertainment: Musicals & Theatres' },
  { key: 14, value: 'Entertainment: Television' },
  { key: 15, value: 'Entertainment: Video Games' },
  { key: 16, value: 'Entertainment: Board Games' },
  { key: 17, value: 'Science & Nature' },
  { key: 18, value: 'Science: Computers' },
  { key: 19, value: 'Science: Mathematics' },
  { key: 20, value: 'Mythology' },
  { key: 21, value: 'Sports' },
  { key: 22, value: 'Geography' },
  { key: 23, value: 'History' },
  { key: 24, value: 'Politics' },
  { key: 25, value: 'Art' },
  { key: 26, value: 'Celebrities' },
  { key: 27, value: 'Animals' },
  { key: 28, value: 'Vehicles' },
  { key: 29, value: 'Entertainment: Comics' },
  { key: 30, value: 'Science: Gadgets' },
  { key: 31, value: 'Entertainment: Japanese Anime & Manga' },
  { key: 32, value: 'Entertainment: Cartoon & Animations' },
];
